### ISSUE TITLE
don't save v_planes.exr

### ISSUE THREAD

**Issue by KirillHiddleston** [sunset1995/PanoPlane360#3]
Run our inference script we have to exr files v_planes and h_planes, but v_planes(segmentation) is not saved completely and will not open.

{'h_planes': array([[ 1.0249354,  1.0249354,  1.0249354, ...,  1.0249354,  1.0249354,
         1.0249354],
       [ 1.0249354,  1.0249354,  1.0249354, ...,  1.0249354,  1.0249354,
         1.0249354],
       [ 1.0249354,  1.0249354,  1.0249354, ...,  1.0249354,  1.0249354,
         1.0249354],
       ...,
       [-0.9487685, -0.9487685, -0.9487685, ..., -0.9487685, -0.9487685,
        -0.9487685],
       [-0.9487685, -0.9487685, -0.9487685, ..., -0.9487685, -0.9487685,
        -0.9487685],
       [-0.9487685, -0.9487685, -0.9487685, ..., -0.9487685, -0.9487685,
        -0.9487685]], dtype=float32), 'v_planes': array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ............................

predict v_planes is empty

Can u help ?

**Comment by sunset1995** [comment]
Exr file of `v_planes` stores the plane parameter in each pixel.
Pixel of a plane share the same plane parameter and `[0,0,0]` is the non-planar special case.

Can you check some statistic of your `v_planes` to ensure that the result is actually empty?
Below is the statistic for `static/mp3d_model_results/demo.v_planes.exr`.
```python
>>> v_planes.shape
(352, 1024, 3)
>>> np.unique(v_planes.reshape(-1,3), axis=0)
array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.84411621e-03, -1.00000000e+00,  4.04296875e+00],
       [ 1.07040405e-02, -1.00000000e+00,  1.77636719e+00],
       [ 1.08642578e-02, -1.00000000e+00,  1.72851562e+00],
       [ 2.26135254e-02,  9.99511719e-01, -3.42968750e+00],
       [ 3.31726074e-02, -9.99511719e-01, -3.39257812e+00],
       [ 3.50036621e-02, -9.99511719e-01,  1.08984375e+00],
       [ 4.20532227e-02, -9.99023438e-01,  1.66894531e+00],
       [ 1.14685059e-01,  9.93164062e-01,  3.33251953e-01],
       [ 1.61499023e-01, -9.86816406e-01, -8.00292969e-01],
       [ 9.62890625e-01, -2.69287109e-01, -9.64843750e-01],
       [ 9.93652344e-01,  1.14501953e-01,  2.66992188e+00],
       [ 9.99023438e-01, -4.08020020e-02,  1.04101562e+00],
       [ 9.99023438e-01,  4.49523926e-02, -1.32226562e+00],
       [ 1.00000000e+00, -1.38092041e-02, -5.88378906e-01],
       [ 1.00000000e+00, -8.64505768e-04, -1.23242188e+00],
       [ 1.00000000e+00,  1.38378143e-03,  2.54296875e+00],
       [ 1.00000000e+00,  2.09960938e-02, -1.27636719e+00]], dtype=float32)
```

You may also want to use the `vis_planes.py` to visualize the result.

**Comment by KirillHiddleston** [comment]
I get the following result after starting the inference on demo.png - static/mp3d_model_results/demo.v_planes.exr and demo.h_planes.exr
But v_planes - the file size is 6 kb and in your example it is 120 kb

After rendering `vis_planes.py` , the walls are not displayed

```
'v_planes': array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)}
```

**Comment by KirillHiddleston** [comment]
just install imageio==2.2 fix bug, pls create requirements
